version: "3"

services:
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
  server:
    build: .
    image: server-image
    container_name: server-image
    command: python3 /app/src/app.py
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - REDIS_HOST=redis
  rq-worker:
    image: jaredv/rq-docker:0.0.2
    command: rq worker --path app/src --url redis://redis:6379 nomenclature document
    deploy:
      replicas: 3
    depends_on:
      - redis
  rq-dashboard:
    image: jaredv/rq-docker:0.0.2
    command: rq-dashboard -H redis
    ports:
      - 9181:9181
    depends_on:
      - redis
