# fly.toml app configuration file generated for datastep-backend-mock on 2023-08-28T12:56:35+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datastep-backend-mock"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
