# fly.toml app configuration file generated for msu-backend on 2023-08-09T14:50:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "msu-backend"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
