[tool.poetry]
name = "msu-backend"
version = "0.1.0"
description = ""
authors = ["Dmitry Bleschunov <bleshunov5b@yandex.ru>"]
readme = "README.md"
packages = [{include = "msu_backend"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = ">=0.101.0,<0.102.0"
uvicorn = ">=0.23.2,<0.24.0"
pydantic = "^2"
pandas = ">=2.0.3,<2.1.0"
pyodbc = ">=4.0.34,<4.1.0"
psycopg2-binary = ">=2.9.7,<2.10.0"
openai = ">=0.27.8,<0.28.0"
tiktoken = ">=0.4.0,<0.5.0"
tabulate = ">=0.9.0,<0.10.0"
starlette = ">=0.27.0,<0.28.0"
supabase = "^1.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
